# Connecting to headless instance with:
# neovide --server /tmp/nvimsocket.sock %F

vsync = false
idle = true
title-hidden = true
frame = "none"
fork = false

[font]
normal = ["MonaspaceNeon Nerd Font"]
size = 7
allow_float_size = true

[font.features]
"MonaspaceNeon Nerd Font" = [
    "+ss01",
    "+ss02",
    "+ss03",
    "+ss04",
    "+ss05",
    "+ss06",
    "+ss07",
    "+ss08",
    "+calt",
    "+liga",
    "+dlig",
]
