theme = "gruvbox-hard"

[editor]
scrolloff = 8
true-color = true
rulers = [120]
idle-timeout = 10
line-number = "relative"

[editor.lsp]
display-messages = true

[editor.file-picker]
# Ignore options
hidden = false

[keys.normal]
"A-W" = ":w"
"G" = "goto_last_line"
H = "goto_first_nonwhitespace"
"minus" = "match_brackets"

[keys.normal.space.w]
b = ":bc"
[keys.normal.C-w]
b = ":bc"
