theme = "kaolin-dark-transparent"

[editor]
color-modes = true
line-number = "relative"
cursorline = false
idle-timeout = 200
completion-trigger-len = 2
rulers = [100]

[editor.lsp]
display-messages = true
auto-signature-help = false

[editor.file-picker]
hidden = false

[keys.normal.space]
# buffer
b.b = "buffer_picker"
b.s = ":write"
b.f = ":format"
b.n = ":new"
b.c = ":buffer-close"
b.a = "select_all"
# options toggle
o.h = ":toggle lsp.display-inlay-hints"
o.H = ":toggle file-picker.hidden"

[keys.normal]
esc = ["collapse_selection", "keep_primary_selection"]
C-u = ["half_page_up", "goto_window_center"]
C-d = ["half_page_down", "goto_window_center"]
";" = "repeat_last_motion"
"minus" = "trim_selections"

### EVIL mode
0 = "goto_line_start"
"$" = "goto_line_end"
"#" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
"^" = "match_brackets"
V = ["select_mode", "extend_to_line_bounds"]
C = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection", "insert_mode"]
D = ["extend_to_line_end", "yank_main_selection_to_clipboard", "delete_selection"]
S = "surround_add"
x = "delete_selection"
p = ["paste_clipboard_after", "collapse_selection"]
P = ["paste_clipboard_before", "collapse_selection"]
Y = ["extend_to_line_end", "yank_main_selection_to_clipboard", "collapse_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
i = ["insert_mode", "collapse_selection"]
a = ["append_mode", "collapse_selection"]

u = ["undo", "collapse_selection"]
C-r = ["redo"]

[keys.normal.d]
d = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection"]
j = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
down = ["select_mode", "extend_to_line_bounds", "extend_line_below", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
k = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
up = ["select_mode", "extend_to_line_bounds", "extend_line_above", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
G = ["select_mode", "extend_to_line_bounds", "goto_last_line", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]
w = ["move_next_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
W = ["move_next_long_word_start", "yank_main_selection_to_clipboard", "delete_selection"]
g.g = ["select_mode", "extend_to_line_bounds", "goto_file_start", "extend_to_line_bounds", "yank_main_selection_to_clipboard", "delete_selection", "normal_mode"]

[keys.select]
0 = "goto_line_start"
"$" = "goto_line_end"
"#" = "goto_first_nonwhitespace"
G = "goto_file_end"
"%" = "match_brackets"
"^" = "match_brackets"
D = ["extend_to_line_bounds", "delete_selection", "normal_mode"]
i = "select_textobject_inner"
a = "select_textobject_around"
J = ["extend_line_down", "extend_to_line_bounds"]
K = ["extend_line_up", "extend_to_line_bounds"]

d = ["yank_main_selection_to_clipboard", "delete_selection"]
x = ["yank_main_selection_to_clipboard", "delete_selection"]
y = ["yank_main_selection_to_clipboard", "normal_mode", "flip_selections", "collapse_selection"]
Y = ["extend_to_line_bounds", "yank_main_selection_to_clipboard", "goto_line_start", "collapse_selection", "normal_mode"]
p = "replace_selections_with_clipboard"
P = "paste_clipboard_before"
  
esc = ["collapse_selection", "keep_primary_selection", "normal_mode"]

[keys.insert]
esc = ["collapse_selection", "normal_mode"]
"C-space" = "completion"
