theme = "gruvbox-hard"

[editor]
scrolloff = 8
true-color = true
rulers = [120]
idle-timeout = 10

[editor.lsp]
display-messages = true

[editor.file-picker]
# Ignore options
hidden = false

[editor.whitespace.render]
newline = "all"

[keys.normal]
"A-W" = ":w"
l = "find_till_char"
L = "till_prev_char"
k = "search_next"
K = "search_prev"
j = "select_regex"
J = "split_selection"
"A-j" = "split_selection_on_newline"
t = "move_line_down"
T = "no_op"
n = "move_line_up"
N = "no_op"
s = "move_char_right"
S = "goto_line_end"
H = "goto_first_nonwhitespace"
"ret" = ["open_below", "normal_mode"]
"minus" = "match_brackets"
[keys.normal.g]
s = "goto_line_end"
h = "goto_first_nonwhitespace"
l = "goto_line_start"
[keys.normal.C-w]
t = "jump_view_down"
n = "jump_view_up"
s = "jump_view_right"
T = "swap_view_down"
N = "swap_view_up"
S = "swap_view_right"
"minus" = "hsplit"
[keys.normal.space.w]
t = "jump_view_down"
n = "jump_view_up"
s = "jump_view_right"
T = "swap_view_down"
N = "swap_view_up"
S = "swap_view_right"
"minus" = "hsplit"

[keys.select]
H = "extend_to_line_start"
s = "extend_char_right"
S = "extend_to_line_end"
t = "extend_line_down"
T = "extend_line"
n = "extend_line_up"
N = "extend_line_above"
l = "extend_till_char"
L = "extend_till_prev_char"
k = "extend_search_next"
K = "extend_search_prev"
j = "select_regex"
J = "split_selection"